
version: '3'

services:
  php-fpm:
    build: ./docker/php-fpm
    container_name: gentela_php
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
  nginx:
    image: nginx:latest
    container_name: gentela_nginx
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
networks:
  default:
    external:
      name: develop
